name:
  length:
    maximum: 50
email:
  length:
    maximum: 255
gravatar:
  size:
    default: 80
    small: 50
    tiny: 30
password:
  length:
    minimum: 6
password_reset_expired: 2
picture:
  size:
    maximum: 5
remember_me:
  checked: "1"
quantity:
  zero: 0
  one: 1
development:
  host: "localhost:3000"
paginate:
  order:
    per_page: 5
  product:
    per_page: 20
